# NUMPY LIBRARY

In [1]:
import time
import sys
import numpy as np

# Time::(list vs array)

# List

In [11]:
t=time.time()
x=range(100000)
y=range(100000)
z=[[i+j] for i,j in zip(x,y)]
print("timeconsume::",(time.time()-t)*1000)

timeconsume:: 70.06406784057617


# array

In [16]:
import numpy as np
t=time.time()
x=np.arange(100000)
y=np.arange(100000)
z=x+y
print("timeconsume::",(time.time()-t)*1000)

timeconsume:: 11.016845703125


# size(list vs array)

In [17]:
b=[9,0,56,45,34,78,93,23,78]
print("list memory size::")
print(sys.getsizeof(9)*len(b))
a=np.array([9,0,56,45,34,78,93,23,78])
print("array memory size::")
print(a.size*a.itemsize)

list memory size::
252
array memory size::
36


# numpy array operations

In [18]:
print("one dimentional array:")
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print("two dimentional array:")
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print("three dimentional array:")
c=np.array([[[1,2,3,4],[5,6,7,8]],[[6,9,0,8],[4,5,3,2]]])
print(c)

one dimentional array:
[1 2 3 4 5 6 7 8 9]
two dimentional array:
[[1 2 3 4]
 [5 6 7 8]]
three dimentional array:
[[[1 2 3 4]
  [5 6 7 8]]

 [[6 9 0 8]
  [4 5 3 2]]]


In [23]:
print("array with zeros:")
print(np.zeros((3,2)))
print("array with ones:")
print(np.ones((3,2)))

array with zeros:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
array with ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
a=np.array([[2,3,4,5],[2,4,5,6],[90,80,67,45]])
print("shape:"+str(a.shape))
print("array size",a.size)
print("array dimensions:",a.ndim)
print("size of each element in array:",a.itemsize)

shape:(3, 4)
array size 12
array dimensions: 2
size of each element in array: 4


In [27]:
print("Array before modification :")
print(a)
print("transpose matrix of matrix a:")
print(a.transpose())
b=a.reshape((2,2,3))
print("Array after modification :")
print(b)

Array before modification :
[[ 2  3  4  5]
 [ 2  4  5  6]
 [90 80 67 45]]
transpose matrix of matrix a:
[[ 2  2 90]
 [ 3  4 80]
 [ 4  5 67]
 [ 5  6 45]]
Array after modification :
[[[ 2  3  4]
  [ 5  2  4]]

 [[ 5  6 90]
  [80 67 45]]]


In [36]:
print(b)
print("==================")
print("==================")
print(b.flatten())
print(b.flatten('f'))

[[[ 2  3  4]
  [ 5  2  4]]

 [[ 5  6 90]
  [80 67 45]]]
[ 2  3  4  5  2  4  5  6 90 80 67 45]
[ 2  5  5 80  3  6  2 67  4 90  4 45]


# numpy - strings:

In [43]:
l1=['a','b','c','d']
l2=['e','f','g','h']
print("list concatination")
print(l1+l2)
a1=np.array(['a','b','c','d'])
a2=np.array(['e','f','g','h'])
print("array concatination")
print(np.char.add(a1,a2))
print("list multiplication:")
print(l1*5)
print("array multiplication:")
print(np.char.multiply(a1,5))

list concatination
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
array concatination
['ae' 'bf' 'cg' 'dh']
list multiplication:
['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']
array multiplication:
['aaaaa' 'bbbbb' 'ccccc' 'ddddd']


In [7]:
import numpy as np
print(np.char.center('hello',20,fillchar="-"))
print(np.char.split("hello! i m fine"))
print(np.char.splitlines("hello! i m fine \n i m going to mumbai"))
print(np.char.strip("amulya is an angle",'a'))
print(np.char.join(['*','/','?'],['amulya','anusha','anitha']))
print(np.char.replace('ravi plays well','plays','sings'))

-------hello--------
['hello!', 'i', 'm', 'fine']
['hello! i m fine ', ' i m going to mumbai']
mulya is an angle
['a*m*u*l*y*a' 'a/n/u/s/h/a' 'a?n?i?t?h?a']
ravi sings well


In [8]:
#font::
print("capitalizing::",end=" ")
print(np.char.capitalize('ravi plays well'))
print("title::",end=" ")
print(np.char.title('ravi plays well'))
print("uppercase::",end=" ")
print(np.char.upper('ravi plays well'))
print("lowercase::",end=" ")
print(np.char.lower('ravi plays well'))

capitalizing:: Ravi plays well
title:: Ravi Plays Well
uppercase:: RAVI PLAYS WELL
lowercase:: ravi plays well


# arithmetic operations on arrays

In [10]:
a1=np.array([[60,78,56,45],[39,24,56,78]])
a2=np.array([[2,4,6,7],[9,6,3,8]])
print("addition:")
print(a1+a2)
print("============================")
print("sutraction:")
print(a1-a2)
print("============================")
print("multiplication:")
print(a1*a2)
print("============================")
print("division:")
print(a1/a2)
print("============================")
print("flow division:")
print(a1//a2)
print("============================")
print("modulo:")
print(a1%a2)

addition:
[[62 82 62 52]
 [48 30 59 86]]
sutraction:
[[58 74 50 38]
 [30 18 53 70]]
multiplication:
[[120 312 336 315]
 [351 144 168 624]]
division:
[[30.         19.5         9.33333333  6.42857143]
 [ 4.33333333  4.         18.66666667  9.75      ]]
flow division:
[[30 19  9  6]
 [ 4  4 18  9]]
modulo:
[[0 2 2 3]
 [3 0 2 6]]


In [14]:
a1=np.array([[60,78,56,45],[39,24,56,78]])
a2=np.array([2,4,6,8])
print(a1+a2)

[[62 82 62 53]
 [41 28 62 86]]


# slicing of an array

In [19]:
a2=np.array([2,4,6,8,7,8,9,0,4,6,8])
print(a2[4:])
print(a2[:4])
print(a2[4:-5])
s=slice(2,7,2)
print(a2[s])

[7 8 9 0 4 6 8]
[2 4 6 8]
[7 8]
[6 7 9]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,6,7],[9,8,7,4]])
print(a)
print('=================================')
print(a[0:3,1:3])

[[1 2 3 4]
 [2 3 4 5]
 [3 4 6 7]
 [9 8 7 4]]
[[2 3]
 [3 4]
 [4 6]]


# iterating array elements

In [15]:
a=np.array([[1,2,3,4],[45,67,56,78],[12,23,34,45]])
print(type(a))
for x in a:
    print(x)
print("========================")
for y in np.nditer(a):
    print(y,end=" ")
print()
print("========================")
for y in np.nditer(a,order='F'):
    print(y,end=" ")

<class 'numpy.ndarray'>
[1 2 3 4]
[45 67 56 78]
[12 23 34 45]
1 2 3 4 45 67 56 78 12 23 34 45 
1 45 12 2 67 23 3 56 34 4 78 45 

# joining arrays

In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(a)
print("==================")
print(b)
print("====================")
print(np.concatenate((a,b)))
print("====================")
print(np.concatenate((a,b),axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]


In [21]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b=np.resize(a,(4,4))
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]
 [1 2 3 4]]
(4, 4)


# some useful functions in numpy:

In [22]:
a=np.linspace(6,12,15)
print(a)

[ 6.          6.42857143  6.85714286  7.28571429  7.71428571  8.14285714
  8.57142857  9.          9.42857143  9.85714286 10.28571429 10.71428571
 11.14285714 11.57142857 12.        ]


In [25]:
a=np.array([[1,3,6],[22,88,99]])
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))

219
[ 23  91 105]
[ 10 209]
[[1.         1.73205081 2.44948974]
 [4.69041576 9.38083152 9.94987437]]
40.99085263811915


# useful/practice models:

In [25]:
z=np.random.rand(10,10)
print(z)
print('=====================================================================')
z[np.random.randint(10,size=10),np.random.randint(10,size=10)]=np.nan
print(z)

[[0.63665154 0.67965917 0.91699886 0.22052872 0.02270749 0.99468251
  0.56114439 0.62155446 0.89687362 0.48897382]
 [0.5317287  0.53841759 0.78911301 0.74793116 0.83830945 0.86002204
  0.16448324 0.42173172 0.44834543 0.42432408]
 [0.97673014 0.63134713 0.40201589 0.87806184 0.53942097 0.11359092
  0.22004978 0.37343337 0.75184412 0.06243137]
 [0.03763641 0.33970233 0.68569104 0.87283316 0.14129061 0.03293956
  0.85263883 0.25881875 0.38332935 0.98536239]
 [0.30039027 0.27526081 0.88618956 0.20860839 0.2299211  0.92576701
  0.2445265  0.81891356 0.50689301 0.05141613]
 [0.5712144  0.31476897 0.13541844 0.60695317 0.11179242 0.9132487
  0.71810761 0.40337261 0.15735971 0.74995451]
 [0.30033219 0.8900699  0.77210311 0.34855551 0.68489454 0.96719593
  0.75752259 0.1450308  0.57769719 0.28557481]
 [0.79201536 0.21232117 0.73522387 0.29739208 0.33201742 0.3542834
  0.22363842 0.38142775 0.88403029 0.18038762]
 [0.7100685  0.02546146 0.02689064 0.05261959 0.06794628 0.38075666
  0.35645473 0

In [27]:
print("no of missing values in array:",np.isnan(z).sum())
print("index of missing values:")
inds=np.where(np.isnan(z))
print(inds)
z[inds]=0

no of missing values in array: 10
index of missing values:
(array([0, 2, 2, 3, 4, 5, 6, 7, 7, 9], dtype=int64), array([9, 0, 1, 1, 3, 1, 6, 4, 5, 1], dtype=int64))
mean nan


In [28]:
z

array([[0.63665154, 0.67965917, 0.91699886, 0.22052872, 0.02270749,
        0.99468251, 0.56114439, 0.62155446, 0.89687362, 0.        ],
       [0.5317287 , 0.53841759, 0.78911301, 0.74793116, 0.83830945,
        0.86002204, 0.16448324, 0.42173172, 0.44834543, 0.42432408],
       [0.        , 0.        , 0.40201589, 0.87806184, 0.53942097,
        0.11359092, 0.22004978, 0.37343337, 0.75184412, 0.06243137],
       [0.03763641, 0.        , 0.68569104, 0.87283316, 0.14129061,
        0.03293956, 0.85263883, 0.25881875, 0.38332935, 0.98536239],
       [0.30039027, 0.27526081, 0.88618956, 0.        , 0.2299211 ,
        0.92576701, 0.2445265 , 0.81891356, 0.50689301, 0.05141613],
       [0.5712144 , 0.        , 0.13541844, 0.60695317, 0.11179242,
        0.9132487 , 0.71810761, 0.40337261, 0.15735971, 0.74995451],
       [0.30033219, 0.8900699 , 0.77210311, 0.34855551, 0.68489454,
        0.96719593, 0.        , 0.1450308 , 0.57769719, 0.28557481],
       [0.79201536, 0.21232117, 0.7352238